### PR TITLE
Add the Goerli support in keymap

### PR DESCRIPTION
**Pull request by koshilife**
Hi maintainers,

This PR is to add the Goerli, which is an Ethereum testnet.
Could you review this?

### Background

I'm a [Blockcerts.org](https://www.blockcerts.org/) user and contributor.
Now, the Blockcerts module [cert-verifier-js](https://github.com/blockchain-certificates/cert-verifier-js) has been using this npm and support only the Ropsten in Ethereum testnets.

Ethereum announced that the Ropsten will be closed in Q4 2022.
So, We have planned at [this page](https://community.blockcerts.org/t/ethereum-announced-the-testnet-ropsten-would-be-closed-in-q4-2022/3227) to support recommended testnets Goerli and Sepolia.

### Refs

- [Goerli info](https://github.com/eth-clients/goerli)

>Network ID: 5
>Chain ID: 5

- #18

### CODE REVIEW

**Comment by koshilife** [comment]
Hi @dsemenovsky,
Could you have a chance to review this?

**Comment by dsemenovsky** [comment]
No, I no longer maintain this.

Dmitry Semenovsky
+1 (416) 455-0212

Sent via Superhuman iOS ***@***.***>

**Comment by koshilife** [comment]
Thanks for replying.
I understood.

**Comment by lemoustachiste** [comment]
@dsemenovsky ok if I fork the repo to blockcerts org, and publish npm under that umbrella too?

**Pull request merged**
